name: Install + Test + Build
on:
  push:
    branches:
      - "*"
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    container: node:14.15-alpine
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn test
      - run: yarn build
